import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Session from "./session";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <Session>
        <body className={`${inter.className} bg-slate-800 text-slate-50`}>
          {children}
        </body>
      </Session>
    </html>
  );
}
